### ISSUE TITLE
cannot import module BaggingClassifier

### ISSUE THREAD

**Issue by avilella** [EpistasisLab/scikit-mdr#22]
I tried to install scikit-mdr on an Ubuntu 14.04 Linux via pip install but got this error below. To make sure it wasn't a versions issue with scikit-learn, I did a `sudo pip install -U scikit-learn`, which completed successfully, then tried to load MDR on a python console. See below.

Any ideas?

```
Successfully installed scikit-learn
Cleaning up...
avilella@ubuntu14:~$ 
avilella@ubuntu14:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mdr import MDR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mdr/__init__.py", line 23, in <module>
    from .mdr_ensemble import MDREnsemble
  File "/usr/local/lib/python2.7/dist-packages/mdr/mdr_ensemble.py", line 26, in <module>
    from sklearn.ensemble import BaggingClassifier
ImportError: cannot import name BaggingClassifier
```

**Comment by rhiever** [comment]
One of the scikit-MDR algorithms uses scikit-learn's [BaggingClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html), which should be available in your installation of scikit-learn.

What version of scikit-learn is installed?

```Python
import sklearn
print sklearn.__version__
```

**Comment by avilella** [comment]
avilella@ubuntu14:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> print sklearn.__version__
0.14.1

**Comment by rhiever** [comment]
That explains it. The latest version of scikit-learn is 0.19, and the BaggingClassifier was probably added after 0.14.1.

If you use the [Anaconda distribution](https://www.continuum.io/downloads), I believe they have scikit-learn up-to-date for Python 2.7.
